name: Self Host Runner

on:
  pull_request:
    paths:
    - '.github/workflows/reposcore.yml'
    # Runs at every pull requests submitted in master branch
    branches: [ main ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          sudo apt-get install python3-setuptools
          sudo pip3 install -r requirements.txt
          sudo PBR_VERSION=1.100.0 python3 setup.py install
          sudo rm -rf build reposcore.egg-info
          sudo GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} reposcore -c etc/reposcore.conf --project-list ~/score/final.txt --result-file ~/score/$(date "+%Y%m%d-%H%M").txt --auto-update
